version: '3'
services:
  manager-nginx:
    build:
      context: ./manager/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./manager:/app
    depends_on:
      - manager-php-fpm
    ports:
      - "8090:80"
      - "8099:80"
  manager-php-fpm:
    build:
      context: ./manager/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./manager:/app
  manager-php-cli:
    build:
      context: ./manager/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./manager:/app
      - composer:/root/.composer/cache
    tty: true
  manager-postgres:
    image: postgres:11.2-alpine
    volumes:
      - manager-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54322:5432"
  manager-node:
    image: node:12.7-alpine
    volumes:
      - ./manager:/app
    working_dir: /app
  manager-node-watch:
    image: node:12.7-alpine
    volumes:
      - ./manager:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  manager-redis:
    image: redis:5.0-alpine
    volumes:
      - manager-redis:/data
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass secret'
  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw
    ports:
      - 9203:9200
    restart: unless-stopped
  kibana:
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    ports:
      - 5605:5601
    restart: unless-stopped
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
    restart: unless-stopped
volumes:
  manager-postgres:
  manager-redis:
  composer:
  elasticsearch:
    driver: local
  logstash: