doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate:

        types:
            user_user_id:
                class: 'App\Model\User\Entity\User\Type\IdType'
                commented: false
            user_company_id:
                class: 'App\Model\Company\Entity\Type\IdType'
                commented: false
            user_company_inn:
                class: 'App\Model\Company\Entity\Type\InnType'
                commented: false
            user_user_email:
                class: 'App\Model\User\Entity\User\Type\EmailType'
                commented: false
            user_user_role:
                class: 'App\Model\User\Entity\User\Type\RoleType'
            work_members_group_id:
                class: 'App\Model\Work\Entity\Members\Group\IdType'
            work_members_member_id:
                class: 'App\Model\Work\Entity\Members\Member\IdType'
            work_members_member_email:
                class: 'App\Model\Work\Entity\Members\Member\EmailType'
            work_members_member_status:
                class: 'App\Model\Work\Entity\Members\Member\StatusType'
            shop_product_products_id:
                class: 'App\Model\Shop\Entity\Product\Type\IdType'
                commented: false
            user_info_id:
                class: 'App\Model\User\Entity\UserInfo\Type\IdType'
                commented: false
            work_projects_project_id:
                class: 'App\Model\Work\Entity\Projects\Project\IdType'
            work_projects_project_status:
                class: 'App\Model\Work\Entity\Projects\Project\StatusType'
            work_projects_project_department_id:
                class: 'App\Model\Work\Entity\Projects\Project\Department\IdType'
            work_projects_role_id:
                class: 'App\Model\Work\Entity\Projects\Role\IdType'
            work_projects_role_permissions:
                class: 'App\Model\Work\Entity\Projects\Role\PermissionsType'

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        second_level_cache:
            region_cache_driver:
                type: service
                id: redis_cache_service
            enabled: true
            region_lifetime: 86400
        metadata_cache_driver:
            type: service
            id: redis_cache_service
        result_cache_driver:
            type: service
            id: redis_cache_service
        query_cache_driver:
            type: service
            id: redis_cache_service
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Company:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Company/Entity'
                prefix: 'App\Model\Company\Entity'
                alias: Company
            Shop:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Shop/Entity'
                prefix: 'App\Model\Shop\Entity'
                alias: Shop
            Work:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Work/Entity'
                prefix: 'App\Model\Work\Entity'
                alias: Work