doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate:

        types:
            user_user_id:
                class: 'App\Model\User\Entity\Type\IdType'
                commented: false
            user_company_id:
                class: 'App\Model\User\Entity\Type\IdType'
                commented: false
            user_user_email:
                class: 'App\Model\User\Entity\Type\EmailType'
                commented: false
            user_user_role:
                class: 'App\Model\User\Entity\Type\RoleType'

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        second_level_cache:
            enabled: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Company:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Company/Entity'
                prefix: 'App\Model\Company\Entity'
                alias: Company